version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astro_ssr_app
    restart: always

    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 6500

    ports:
      - "7500:6500"
    extra_hosts:
      - "host.docker.internal:host-gateway"
